const rubric = {
  weight: {
    id: "totalWeight",
    label: "Total Game Weight",
    max: 30,
    help: "Use BGG listed weight, publisher weight, or weigh it yourself. Impacts scale roughly linearly with total mass per LCA research.",
    units: [
      { value: "g", label: "Grams" },
      { value: "kg", label: "Kilograms" },
      { value: "oz", label: "Ounces" },
      { value: "lb", label: "Pounds" },
    ],
    brackets: [
      { min: 0, max: 300, points: 30, label: "Under 300g" },
      { min: 300, max: 600, points: 24, label: "300g-600g" },
      { min: 600, max: 1200, points: 18, label: "600g-1.2 kg" },
      { min: 1200, max: 2000, points: 12, label: "1.2-2.0 kg" },
      { min: 2000, max: 3500, points: 6, label: "2.0-3.5 kg" },
      { min: 3500, max: Infinity, points: 0, label: "Over 3.5 kg" },
    ],
  },
  baseCriteria: [
    {
      id: "materialMix",
      label: "2. End-of-Life Material Mix",
      max: 10,
      options: [
        { points: 10, label: "Predominantly paper, cardboard, or wood with minimal additives or coatings; components are mostly mono-material and designed for easy recovery or low persistence in waste streams" },
        { points: 7, label: "Mostly paper/cardboard/wood; some coated or composite elements that reduce recovery potential" },
        { points: 4, label: "Significant mixed materials, laminates, foils, or moderate plastic components (inserts, bags, light minis) that are likely to end up in landfill or as persistent waste" },
        { points: 2, label: "Heavy reliance on plastic components (minis, trays, etc.) with no practical recovery pathway in most regions" },
        { points: 0, label: "Dominated by mixed or bonded plastics, non-recyclable composites, or materials that are effectively landfill-bound or persistent regardless of sorting efforts" },
      ],
    },
    {
      id: "packagingPlastic",
      label: "3. Packaging Plastic",
      max: 5,
      options: [
        { points: 5, label: "No single-use plastic packaging (paper wrap or stickers, no bags, cardboard organizer)" },
        { points: 3, label: "Minimal plastic (biodegradable bags or one small tray)" },
        { points: 1, label: "Standard plastic insert, bags, shrink wrap" },
        { points: 0, label: "Excessive disposable plastic (oversized vacuum trays, blister packs, heavy bagging)" },
      ],
    },
    {
      id: "packagingEfficiency",
      label: "4. Packaging Efficiency",
      max: 10,
      options: [
        { points: 10, label: "Small or modest box, tightly packed, minimal air — box sized to contents" },
        { points: 8, label: "Efficient use of space; box matches contents well" },
        { points: 5, label: "Standard box with moderate wasted space" },
        { points: 2, label: "Oversized box for shelf presence or marketing; significant empty volume" },
        { points: 0, label: "Enormous box mostly transporting air" },
      ],
    },
    {
      id: "durability",
      label: "5. Durability / Lifespan",
      max: 10,
      options: [
        { points: 10, label: "Very durable; likely decades of play. Standard-sleeved cards, solid boards, replacement parts available" },
        { points: 8, label: "Strong longevity; good component quality, sleeve-compatible cards" },
        { points: 5, label: "Moderate wear expected; odd card sizes (hard to sleeve), thin cardboard" },
        { points: 2, label: "Components likely to wear, chip, delaminate, or need replacement quickly" },
        { points: 0, label: "Fragile or quasi-disposable; legacy/destructible components" },
      ],
    },
    {
      id: "expectedUse",
      label: "6. Expected Use Intensity",
      max: 10,
      options: [
        { points: 10, label: "Very high expected plays (50+); small physical footprint per play-hour" },
        { points: 8, label: "Strong expected use (20-50 plays); campaign game, expandable system, or high-variety design" },
        { points: 5, label: "Moderate expected use (10-20 plays); standard hobby game" },
        { points: 2, label: "Limited expected use (under 10 plays) relative to physical size" },
        { points: 0, label: "Essentially single-use (legacy/destructible) or novelty with minimal replay" },
      ],
    },
    {
      id: "supplyChain",
      label: "7. Supply Chain / Geography",
      max: 7,
      options: [
        { points: 7, label: "Manufactured in same country as primary market" },
        { points: 5, label: "Manufactured on same continent as primary market" },
        { points: 2, label: "Manufactured overseas (industry default — container shipping)" },
        { points: 0, label: "Manufacturing location unknown / undisclosed" },
      ],
    },
  ],
  penalties: [
    { id: "shrinkWrap", points: -3, label: "Excessive shrink wrap / plastic overwrap beyond industry standard" },
    { id: "oversizedInsert", points: -3, label: "Non-functional oversized insert (box filler, not organizer)" },
    { id: "foilFinish", points: -5, label: "Foil, laminate, or hard-to-recycle finish on many components" },
    { id: "collectorBloat", points: -5, label: "Obvious collector bloat packaging" },
    { id: "oddCardSizes", points: -3, label: "Non-standard card sizes preventing sleeving" },
  ],
  disclosure: {
    id: "disclosure",
    label: "Disclosure / Transparency",
    options: [
      { points: 8, label: "Detailed public product-specific disclosure — materials, weight, sources, manufacturing location per game" },
      { points: 5, label: "Company-level sustainability commitments with some product-specific detail" },
      { points: 2, label: "Public statement beyond marketing; real but vague sustainability claims" },
      { points: -3, label: "No meaningful public disclosure" },
      { points: -7, label: "Actively deceptive claims contradicted by obvious product choices" },
    ],
  },
  verifiedActions: [
    { id: "recycledMaterials", points: 2, label: "Verified recycled or FSC-certified materials" },
    { id: "plasticFreePackaging", points: 2, label: "No shrink wrap / plastic-free packaging initiative" },
    { id: "regionalManufacturing", points: 2, label: "Regional manufacturing strategy (same continent or closer)" },
    { id: "carbonAccounting", points: 2, label: "Carbon accounting or product-level emissions tracking" },
    {
      id: "offsetProgram",
      label: "Credible offset program",
      options: [
        { points: 0, label: "Not applied" },
        { points: 1, label: "+1" },
        { points: 2, label: "+2" },
        { points: 3, label: "+3" },
      ],
    },
  ],
  penaltyCap: -10,
  verifiedActionsCap: 10,
  verifiedActionsGate: 2,
  tiers: [
    {
      id: "light",
      label: "LIGHT",
      min: 72,
      band: "72+",
      description: "Low environmental cost, high efficiency.",
      consumer: "No special considerations. Enjoy your efficient hobby.",
      publisher: "Share your practices openly to raise the bar for the industry.",
    },
    {
      id: "modest",
      label: "MODEST",
      min: 52,
      band: "52–71",
      description: "Reasonable footprint with room for mindful ownership.",
      consumer: "Prioritize play over accumulation. Sleeve cards to extend lifespan. Sell or gift games you no longer use.",
      publisher: "Examine non-functional plastic and packaging. Small material changes move the needle at this level.",
    },
    {
      id: "considerable",
      label: "CONSIDERABLE",
      min: 32,
      band: "32–51",
      description: "Meaningful footprint that benefits from committed use.",
      consumer: "Commit to regular play to justify the footprint. Share or lend rather than shelf-sitting. Recycle packaging carefully.",
      publisher: "Evaluate material substitutions. Publish sustainability disclosures if you have not. This tier is where transparency earns the most trust.",
    },
    {
      id: "heavy",
      label: "HEAVY",
      min: -Infinity,
      band: "Below 32",
      description: "Resource-intensive product. Ownership carries real environmental weight.",
      consumer: "This is an environmental investment. Earn it through long-term use, community sharing, or lighter choices elsewhere in your collection.",
      publisher: "Your product is inherently material-intensive, so stewardship matters more, not less. Carbon reporting, recycled materials, and take-back programs are how you earn trust here.",
    },
  ],
};
